# Site settings
title: Cameron Stanley 
email: me@cameronstanley.com 
description: Creating things and writing about them. 
baseurl: "" 
url: "http://cameronstanley.com"
twitter_username: "@CameronLStanley"
github_username: cameronstanley 

# Build settings
markdown: kramdown
