# Site settings
title: Cameron Stanley 
email: me@cameronstanley.com 
description: Creating things and writing about them. 
baseurl: ""
url: "http://cameronstanley.com"
github_username: "cameronstanley"
hacker_news_username: "cameronstanley"
twitter_username: "@CameronLStanley"
linkedin_username: "cameron-stanley-67930530"

# Build settings
markdown: kramdown
highlighter: rouge

gems:
  - jekyll-assets
  - jekyll-bootstrap-sass

bootstrap:
  assets: true
